spring:
  application:
    name: manager

server:
  port: 8080

logging:
  level:
    com.crackhash: INFO

workers:
  urls: http://localhost:8081,http://localhost:8082,http://localhost:8083
  timeout: 60
